### ISSUE TITLE
Any Plan to support auto load more?

### ISSUE THREAD

**Issue by zubinxiong** [nekocode/Items#2]
- Thank for your library, but I hava some problem about the function about auto load more.
- Is there any plan to support auto load More?
- I‘m trying to extends the recyclerview to achieve this function(or a wrapper adapter). Is there any better way to doing this ?

**Comment by nekocode** [comment]
It will not support this feature because I think that auto load more is not adapter's duty.

**Comment by zubinxiong** [comment]
thanks, So maybe I should  extends RecyclerView to achieve this feature

**Comment by nekocode** [comment]
Yes, you should better to achieve this feature by extending the RecyclerView.
